### ISSUE TITLE
IMC shouldn't be reading secrets

### ISSUE THREAD

**Issue by kahootali** [stakater/IngressMonitorController#316]
Currently IMC lists K8s secrets and based on the key it loads the [data](https://github.com/stakater/IngressMonitorController/blob/master/pkg/secret/secrets.go#L13) from secret through Kubernetes API.
Isn't this a potential security issue? Rather than listing secret from Kubernetes API, it should expect a config on a path, and the user can mount the file from secret. In this way IMC wouldn't be able to read secrets and we can remove the [RBAC](https://github.com/stakater/IngressMonitorController/blob/master/deploy/role.yaml#L18) of listing secrets from IMC

**Comment by ahmedwaleedmalik** [comment]
The plan is to create a CR for the operator configuration. But I didn't get the time to commit to that. 

https://github.com/stakater/IngressMonitorController/issues/265

**Comment by ahmedwaleedmalik** [comment]
In terms of being a security risk, no it isn't. If I have an option to mount a secret or use a very well-defined code to auto-fetch the secret, I'd prefer the latter. Even when the configuration is moved to a CR, it would still refer secret for the value of fields like token etc. since CR shouldn't have any direct secrets.

But yes assigning `ClusterRole` for secrets is probably not the right approach here. We can probably split it down to:
1. ClusterRole for everything else
2. Role for secret, that gives it access to `list, get` secret in the operator namespace.

**Comment by kahootali** [comment]
In my opinion, it would still be a security risk, we would never want any pod to have access to secrets or any resources that it doesn't handle. And if someone gets access to IMC pod, he can easily list the secrets. I would prefer the former in the above scenario.

**Comment by ahmedwaleedmalik** [comment]
Again, as I said. It shouldn't have clusterrole to list secrets and that should be replaced with a namespaced `role`.

**Comment by ahmedwaleedmalik** [comment]
Namespace restricted with #317
