### ISSUE TITLE
defaultRequeueTime configurable 

### ISSUE THREAD

**Issue by adamstrawson** [stakater/IngressMonitorController#347]
Currently `defaultRequeueTime` is a fixed value of `60 * time.Second` - What's your thoughts on making this variable configurable with a default of the current value?

We've recently starting having issues with StatusCake where the API is being rate limited because of the amount of EndpointMonitors we have, and so the polling is hitting our account limit. 

It would be useful for us to be able to increase the amount of time between the monitor being checked again so that we can reduce the API calls to StatusCake.

Happy to open a PR if you think this would be helpful?

**Comment by kahootali** [comment]
I am also facing the same issue, it keeps updating the Monitors resulting in Rate Limiting for Uptime Robot, saw the [configurations](https://github.com/stakater/IngressMonitorController#configuration-parameters), there is a field `resyncPeriod` but it doesn't correspond to the Requeue value

**Comment by ahmedwaleedmalik** [comment]
After retrieving the state of the monitor from the monitor service, we are supposed to compare it with the declared state in the cluster. Right now the method to perform this comparison is not implemented.

https://github.com/stakater/IngressMonitorController/blob/add-requeue-time-flag/pkg/monitors/uptimerobot/uptime-monitor.go#L26

Implementing this would make sure there are no redundant API calls for POST/PUT actions.

I'll handle this in two parts:
- Add `REQUEUE_TIME` environment variable to facilitate end-users for providing their own configuration
- Implement the comparator method for `UptimeRobot` so that we can reduce the number of reconciliations, in general.
